apiVersion: apps/v1
kind: Deployment
metadata:
  name: elaina-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: elaina
  template:
    metadata:
      labels:
        apps: elaina
    spec:
      serviceAccountName: csi-elaina
      containers:
        - name: elaina
          image: container.alibabacloud.repo/arcnadiven/elaina:v0.0.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - /elaina start --db-user=root --db-passwd=123456 --db-host=172.16.215.215 --db-port 3306 --db-name=persistent_volume --log-file=/var/log/elaina/elaina.log
          volumeMounts:
            - mountPath: /var/log/elaina
              name: varlog
            - mountPath: /tmp/
              name: socket-dir
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/elaina/csi.sock
          volumeMounts:
            - mountPath: /registration
              name: registration-dir
            - mountPath: /csi
              name: socket-dir
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/elaina
            type: DirectoryOrCreate
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/elaina
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
---
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-elaina
kind: StorageClass
provisioner: elaina.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-elaina-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-csi-plugin
subjects:
  - kind: ServiceAccount
    name: csi-elaina
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-csi-plugin
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments/status
    verbs:
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-elaina
  namespace: default